# Generated by Django 4.0.10 on 2025-06-23 04:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.CharField(default=main_app.models.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current Account'), ('SALARY', 'Salary Account'), ('FIXED_DEPOSIT', 'Fixed Deposit'), ('RECURRING_DEPOSIT', 'Recurring Deposit')], max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_opened_date', models.DateField()),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='CibilReport',
            fields=[
                ('id', models.CharField(default=main_app.models.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('report_summary', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('risk_factors', models.TextField(blank=True)),
                ('positive_factors', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_version', models.CharField(default='1.0', max_length=10)),
            ],
            options={
                'db_table': 'cibil_reports',
            },
        ),
        migrations.CreateModel(
            name='CibilScore',
            fields=[
                ('id', models.CharField(default=main_app.models.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(900)])),
                ('payment_history_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_utilization_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_history_length_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_mix_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_credit_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_accounts', models.IntegerField(default=0)),
                ('active_accounts', models.IntegerField(default=0)),
                ('total_credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_utilization_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_date', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cibil_scores',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.CharField(default=main_app.models.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('card_number_last_four', models.CharField(max_length=4)),
                ('card_type', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('RUPAY', 'RuPay'), ('AMEX', 'American Express')], max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'credit_cards',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=main_app.models.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('pan_card_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.CharField(default=main_app.models.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('loan_account_number', models.CharField(max_length=50)),
                ('loan_type', models.CharField(choices=[('HOME_LOAN', 'Home Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('CAR_LOAN', 'Car Loan'), ('EDUCATION_LOAN', 'Education Loan'), ('BUSINESS_LOAN', 'Business Loan'), ('GOLD_LOAN', 'Gold Loan')], max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure_months', models.IntegerField()),
                ('remaining_tenure', models.IntegerField()),
                ('loan_start_date', models.DateField()),
                ('loan_end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('OVERDUE', 'Overdue'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='main_app.customer')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.CharField(default=main_app.models.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('LOAN_EMI', 'Loan EMI'), ('CREDIT_CARD', 'Credit Card Bill'), ('UTILITY_BILL', 'Utility Bill'), ('OTHER', 'Other')], max_length=20)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('ON_TIME', 'On Time'), ('LATE_1_30', 'Late (1-30 days)'), ('LATE_31_60', 'Late (31-60 days)'), ('LATE_61_90', 'Late (61-90 days)'), ('LATE_90_PLUS', 'Late (90+ days)'), ('MISSED', 'Missed Payment'), ('DEFAULTED', 'Defaulted')], max_length=20)),
                ('days_late', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.creditcard')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='main_app.customer')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.loan')),
            ],
            options={
                'db_table': 'payment_history',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['pan_card_number'], name='customers_pan_car_ffebfa_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='customers_created_c63477_idx'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='main_app.customer'),
        ),
        migrations.AddField(
            model_name='cibilscore',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cibil_scores', to='main_app.customer'),
        ),
        migrations.AddField(
            model_name='cibilreport',
            name='cibil_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cibilscore'),
        ),
        migrations.AddField(
            model_name='cibilreport',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cibil_reports', to='main_app.customer'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='main_app.customer'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['customer', 'due_date'], name='payment_his_custome_afbeb2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payment_status'], name='payment_his_payment_95bd7f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['created_at'], name='payment_his_created_e5fa9c_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['customer', 'status'], name='loans_custome_81a6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_account_number'], name='loans_loan_ac_6b4126_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcard',
            index=models.Index(fields=['customer', 'is_active'], name='credit_card_custome_b445fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cibilscore',
            index=models.Index(fields=['customer', 'is_latest'], name='cibil_score_custome_b7f077_idx'),
        ),
        migrations.AddIndex(
            model_name='cibilscore',
            index=models.Index(fields=['score_date'], name='cibil_score_score_d_8ba0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='cibilreport',
            index=models.Index(fields=['customer', 'generated_at'], name='cibil_repor_custome_6da52c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['customer', 'is_active'], name='bank_accoun_custome_e59f10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('account_number', 'ifsc_code')},
        ),
    ]
